#!/bin/bash
# restore-from-backup.sh - Helper script for restoring OpenClaw config to Azure VM
# Generated by Tara's Terraform deployment
#
# Usage: ./restore-from-backup.sh <vm-ip> [backup-dir]

set -euo pipefail

# Configuration
VM_IP="${1:-}"
BACKUP_DIR="${2:-${HOME}/clawd-backup}"
ADMIN_USER="${ADMIN_USER:-chloe}"
SSH_KEY="${SSH_KEY:-${HOME}/.ssh/id_rsa}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')]${NC} $*"
}

error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
    exit 1
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $*" >&2
}

usage() {
    cat << EOF
Usage: $0 <vm-ip> [backup-dir]

Restores OpenClaw configuration from backup to Azure VM.

Arguments:
  vm-ip       Public IP address of the Azure VM
  backup-dir  Local backup directory (default: ~/clawd-backup)

Environment Variables:
  ADMIN_USER  VM admin username (default: chloe)
  SSH_KEY     SSH key for authentication (default: ~/.ssh/id_rsa)

Examples:
  $0 20.10.30.40
  $0 20.10.30.40 /path/to/custom/backup
  ADMIN_USER=openclaw $0 20.10.30.40

EOF
    exit 1
}

# Validate inputs
if [[ -z "${VM_IP}" ]]; then
    error "VM IP address is required"
    usage
fi

if [[ ! -d "${BACKUP_DIR}" ]]; then
    error "Backup directory not found: ${BACKUP_DIR}"
fi

SSH_TARGET="${ADMIN_USER}@${VM_IP}"

log "Starting OpenClaw configuration restoration..."
log "VM: ${SSH_TARGET}"
log "Backup source: ${BACKUP_DIR}"

# Test SSH connection
log "Testing SSH connection..."
if ! ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -i "${SSH_KEY}" "${SSH_TARGET}" "exit" 2>/dev/null; then
    error "Cannot connect to ${SSH_TARGET}. Check that:"
    echo "  1. VM is running"
    echo "  2. IP address is correct"
    echo "  3. SSH key is correct (${SSH_KEY})"
    echo "  4. Network Security Group allows your IP"
fi
log "SSH connection successful"

# Create backup directory on VM
log "Creating directories on VM..."
ssh -i "${SSH_KEY}" "${SSH_TARGET}" "mkdir -p ~/backup ~/.openclaw ~/.clawdbot/credentials ~/clawd"

# Upload backup files
log "Uploading backup files (this may take a few minutes)..."
rsync -avz --progress -e "ssh -i ${SSH_KEY}" "${BACKUP_DIR}/" "${SSH_TARGET}:~/backup/"

# Restore configs
log "Restoring OpenClaw configuration..."
ssh -i "${SSH_KEY}" "${SSH_TARGET}" << 'RESTORE_SCRIPT'
set -euo pipefail

BACKUP_DIR="${HOME}/backup"

find_latest() {
    ls -t "${BACKUP_DIR}/$1"/$2 2>/dev/null | head -1
}

echo "Restoring OpenClaw config..."
config_backup=$(find_latest "config" "openclaw-*.tar.gz")
if [[ -n "${config_backup}" ]]; then
    tmpdir=$(mktemp -d)
    tar -xzf "${config_backup}" -C "${tmpdir}"
    extracted=$(ls -d "${tmpdir}"/openclaw-* | head -1)
    
    [[ -f "${extracted}/openclaw.json" ]] && cp -p "${extracted}/openclaw.json" ~/.openclaw/
    [[ -f "${extracted}/cron-jobs.json" ]] && { mkdir -p ~/.openclaw/cron; cp -p "${extracted}/cron-jobs.json" ~/.openclaw/cron/jobs.json; }
    [[ -d "${extracted}/identity" ]] && cp -rp "${extracted}/identity" ~/.openclaw/
    [[ -d "${extracted}/credentials" ]] && cp -rp "${extracted}/credentials" ~/.openclaw/
    [[ -d "${extracted}/agents" ]] && cp -rp "${extracted}/agents" ~/.openclaw/
    [[ -d "${extracted}/memory" ]] && cp -rp "${extracted}/memory" ~/.openclaw/
    [[ -d "${extracted}/devices" ]] && cp -rp "${extracted}/devices" ~/.openclaw/
    
    rm -rf "${tmpdir}"
    echo "✓ OpenClaw config restored"
else
    echo "⚠ No OpenClaw config backup found"
fi

echo "Restoring Clawdbot credentials..."
creds_backup=$(find_latest "credentials" "clawdbot-creds-*.tar.gz")
if [[ -n "${creds_backup}" ]]; then
    mkdir -p ~/.clawdbot
    tar -xzf "${creds_backup}" -C ~/.clawdbot --strip-components=1
    chmod 700 ~/.clawdbot/credentials 2>/dev/null || true
    chmod 600 ~/.clawdbot/credentials/* 2>/dev/null || true
    echo "✓ Clawdbot credentials restored"
else
    echo "⚠ No Clawdbot credentials backup found"
fi

echo "Restoration complete!"
RESTORE_SCRIPT

# Clone workspace
log "Cloning chloe-workspace repository..."
ssh -i "${SSH_KEY}" "${SSH_TARGET}" "git clone https://github.com/drlawler/chloe-workspace.git ~/clawd 2>/dev/null || (cd ~/clawd && git pull)"

# Print next steps
cat << EOF

${GREEN}═══════════════════════════════════════════════════════════════${NC}
${GREEN}          RESTORATION COMPLETE!${NC}
${GREEN}═══════════════════════════════════════════════════════════════${NC}

Config files have been restored to ${SSH_TARGET}

${YELLOW}NEXT STEPS:${NC}

1. Connect to the VM:
   ${GREEN}ssh -i ${SSH_KEY} ${SSH_TARGET}${NC}

2. Update API keys (if needed):
   ${GREEN}nano ~/.openclaw/openclaw.json${NC}
   
   Add/update:
   - ANTHROPIC_API_KEY
   - TELEGRAM_BOT_TOKEN
   - Any other service keys

3. Start OpenClaw:
   ${GREEN}sudo systemctl start openclaw${NC}
   ${GREEN}sudo systemctl status openclaw${NC}

4. Test the deployment:
   ${GREEN}openclaw gateway status${NC}
   ${GREEN}curl http://localhost:8080/health${NC}

5. Check logs:
   ${GREEN}sudo journalctl -u openclaw -f${NC}

${YELLOW}TROUBLESHOOTING:${NC}

If OpenClaw fails to start:
- Check logs: ${GREEN}sudo journalctl -u openclaw -xe${NC}
- Verify config: ${GREEN}cat ~/.openclaw/openclaw.json${NC}
- Test manually: ${GREEN}openclaw gateway start${NC}

${GREEN}═══════════════════════════════════════════════════════════════${NC}

EOF

log "Done! Your OpenClaw instance should be ready to start."
